version: "3.9"

services:
  postgres:
    image: postgres
    restart: unless-stopped
    container_name: postgres
    hostname: postgres
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - keploy-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: letterpressApp
    hostname: api
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - keploy-network

  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:8.10.4'
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=false"
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - keploy-network
  logstash:
    build:
     context: logstash
    container_name: logstash
    env_file: .env
    volumes:
      - ./logstash/pipelines/:/usr/share/logstash/pipeline/
      - ./logstash/queries/:/usr/share/logstash/config/queries/
      - ./logstash/config/pipelines.yml:/usr/share/logstash/config/pipelines.yml
    depends_on:
      - postgres
      - elasticsearch
    networks:
      - keploy-network
  kibana:
    image: 'docker.elastic.co/kibana/kibana:8.10.4'
    ports:
     - "5601:5601"
    container_name: kibana
    hostname: kibana
    environment:
     - "ELASTICSEARCH_URL=http://elasticsearch:9200"
    depends_on:
     - elasticsearch
    networks:
      - keploy-network

volumes:
  pgdata:
    driver: local
  esdata:
    driver: local
networks:
  keploy-network:
    external: true